version: '3'

services:
  web:
    build: .
    command: python app.py
    restart: always
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.0.2
    ports: 
      - "27017:27017"
